# fly.toml app configuration file generated for hanuman-hackathon-backend on 2023-11-18T19:17:18-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hanuman-hackathon-backend"
primary_region = "lax"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
